# Example configuration for Prometheus usable with Gophers.

global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'gophers'
    static_configs:
      - targets: ['127.0.0.1:10311']
