+ Response 201

    + Headers

            Content-Length: 5095
            Access-Control-Allow-Origin: *
            Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
            Cache-Control: private, max-age=60, s-maxage=60
            Content-Security-Policy: default-src 'none'
            Content-Type: application/json; charset=utf-8
            Date: Tue, 29 Mar 2016 11:36:43 GMT
            Etag: "642513588f6cc3a6b70c40c380ffd339"
            Location: https://api.github.com/repos/go-gopher/test-gophers-chaz
            Server: GitHub.com
            Status: 201 Created
            Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
            Vary: Accept, Authorization, Cookie, X-GitHub-OTP
            Vary: Accept-Encoding
            X-Accepted-Oauth-Scopes: public_repo, repo
            X-Content-Type-Options: nosniff
            X-Frame-Options: deny
            X-Github-Media-Type: github.v3; format=json
            X-Github-Request-Id: 0586D966:6B9D:1165FD00:56FA68CB
            X-Oauth-Scopes: delete_repo, public_repo, read:org
            X-Ratelimit-Limit: 5000
            X-Ratelimit-Remaining: 4978
            X-Ratelimit-Reset: 1459254849
            X-Served-By: 76d9828c7e4f1d910f7ba069e90ce976
            X-Xss-Protection: 1; mode=block

    + Body

            {
              "archive_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/{archive_format}{/ref}",
              "assignees_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/assignees{/user}",
              "blobs_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/git/blobs{/sha}",
              "branches_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/branches{/branch}",
              "clone_url": "https://github.com/go-gopher/test-gophers-chaz.git",
              "collaborators_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/collaborators{/collaborator}",
              "comments_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/comments{/number}",
              "commits_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/commits{/sha}",
              "compare_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/compare/{base}...{head}",
              "contents_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/contents/{+path}",
              "contributors_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/contributors",
              "created_at": "2016-03-29T11:36:43Z",
              "default_branch": "master",
              "deployments_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/deployments",
              "description": null,
              "downloads_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/downloads",
              "events_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/events",
              "fork": false,
              "forks": 0,
              "forks_count": 0,
              "forks_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/forks",
              "full_name": "go-gopher/test-gophers-chaz",
              "git_commits_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/git/commits{/sha}",
              "git_refs_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/git/refs{/sha}",
              "git_tags_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/git/tags{/sha}",
              "git_url": "git://github.com/go-gopher/test-gophers-chaz.git",
              "has_downloads": true,
              "has_issues": true,
              "has_pages": false,
              "has_wiki": true,
              "homepage": null,
              "hooks_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/hooks",
              "html_url": "https://github.com/go-gopher/test-gophers-chaz",
              "id": 5.4970737e+07,
              "issue_comment_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/issues/comments{/number}",
              "issue_events_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/issues/events{/number}",
              "issues_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/issues{/number}",
              "keys_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/keys{/key_id}",
              "labels_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/labels{/name}",
              "language": null,
              "languages_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/languages",
              "merges_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/merges",
              "milestones_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/milestones{/number}",
              "mirror_url": null,
              "name": "test-gophers-chaz",
              "network_count": 0,
              "notifications_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/notifications{?since,all,participating}",
              "open_issues": 0,
              "open_issues_count": 0,
              "owner": {
                "avatar_url": "https://avatars.githubusercontent.com/u/18141185?v=3",
                "events_url": "https://api.github.com/users/go-gopher/events{/privacy}",
                "followers_url": "https://api.github.com/users/go-gopher/followers",
                "following_url": "https://api.github.com/users/go-gopher/following{/other_user}",
                "gists_url": "https://api.github.com/users/go-gopher/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/go-gopher",
                "id": 1.8141185e+07,
                "login": "go-gopher",
                "organizations_url": "https://api.github.com/users/go-gopher/orgs",
                "received_events_url": "https://api.github.com/users/go-gopher/received_events",
                "repos_url": "https://api.github.com/users/go-gopher/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/go-gopher/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/go-gopher/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/go-gopher"
              },
              "permissions": {
                "admin": true,
                "pull": true,
                "push": true
              },
              "private": false,
              "pulls_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/pulls{/number}",
              "pushed_at": "2016-03-29T11:36:43Z",
              "releases_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/releases{/id}",
              "size": 0,
              "ssh_url": "git@github.com:go-gopher/test-gophers-chaz.git",
              "stargazers_count": 0,
              "stargazers_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/stargazers",
              "statuses_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/statuses/{sha}",
              "subscribers_count": 1,
              "subscribers_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/subscribers",
              "subscription_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/subscription",
              "svn_url": "https://github.com/go-gopher/test-gophers-chaz",
              "tags_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/tags",
              "teams_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/teams",
              "trees_url": "https://api.github.com/repos/go-gopher/test-gophers-chaz/git/trees{/sha}",
              "updated_at": "2016-03-29T11:36:43Z",
              "url": "https://api.github.com/repos/go-gopher/test-gophers-chaz",
              "watchers": 0,
              "watchers_count": 0
            }