+ Response 201

    + Headers

            Content-Length: 5447
            Access-Control-Allow-Origin: *
            Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
            Cache-Control: private, max-age=60, s-maxage=60
            Content-Security-Policy: default-src 'none'
            Content-Type: application/json; charset=utf-8
            Date: Mon, 08 Aug 2016 17:07:24 GMT
            Etag: "a905dca01157dbc122be94af448bd632"
            Location: https://api.github.com/repos/go-gopher/test-gophers-estelle.rath
            Server: GitHub.com
            Status: 201 Created
            Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
            Vary: Accept, Authorization, Cookie, X-GitHub-OTP
            Vary: Accept-Encoding
            X-Accepted-Oauth-Scopes: public_repo, repo
            X-Content-Type-Options: nosniff
            X-Frame-Options: deny
            X-Github-Media-Type: github.v3; format=json
            X-Github-Request-Id: B9297182:4A48:918ED1C:57A8BC4B
            X-Oauth-Scopes: delete_repo, public_repo, read:org
            X-Ratelimit-Limit: 5000
            X-Ratelimit-Remaining: 4978
            X-Ratelimit-Reset: 1470679342
            X-Served-By: 173530fed4bbeb1e264b2ed22e8b5c20
            X-Xss-Protection: 1; mode=block

    + Body

            {
              "archive_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/{archive_format}{/ref}",
              "assignees_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/assignees{/user}",
              "blobs_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/git/blobs{/sha}",
              "branches_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/branches{/branch}",
              "clone_url": "https://github.com/go-gopher/test-gophers-estelle.rath.git",
              "collaborators_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/collaborators{/collaborator}",
              "comments_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/comments{/number}",
              "commits_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/commits{/sha}",
              "compare_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/compare/{base}...{head}",
              "contents_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/contents/{+path}",
              "contributors_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/contributors",
              "created_at": "2016-08-08T17:07:23Z",
              "default_branch": "master",
              "deployments_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/deployments",
              "description": null,
              "downloads_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/downloads",
              "events_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/events",
              "fork": false,
              "forks": 0,
              "forks_count": 0,
              "forks_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/forks",
              "full_name": "go-gopher/test-gophers-estelle.rath",
              "git_commits_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/git/commits{/sha}",
              "git_refs_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/git/refs{/sha}",
              "git_tags_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/git/tags{/sha}",
              "git_url": "git://github.com/go-gopher/test-gophers-estelle.rath.git",
              "has_downloads": true,
              "has_issues": true,
              "has_pages": false,
              "has_wiki": true,
              "homepage": null,
              "hooks_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/hooks",
              "html_url": "https://github.com/go-gopher/test-gophers-estelle.rath",
              "id": 6.52233e+07,
              "issue_comment_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/issues/comments{/number}",
              "issue_events_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/issues/events{/number}",
              "issues_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/issues{/number}",
              "keys_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/keys{/key_id}",
              "labels_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/labels{/name}",
              "language": null,
              "languages_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/languages",
              "merges_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/merges",
              "milestones_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/milestones{/number}",
              "mirror_url": null,
              "name": "test-gophers-estelle.rath",
              "network_count": 0,
              "notifications_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/notifications{?since,all,participating}",
              "open_issues": 0,
              "open_issues_count": 0,
              "owner": {
                "avatar_url": "https://avatars.githubusercontent.com/u/19872809?v=3",
                "events_url": "https://api.github.com/users/go-gopher/events{/privacy}",
                "followers_url": "https://api.github.com/users/go-gopher/followers",
                "following_url": "https://api.github.com/users/go-gopher/following{/other_user}",
                "gists_url": "https://api.github.com/users/go-gopher/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/go-gopher",
                "id": 1.9872809e+07,
                "login": "go-gopher",
                "organizations_url": "https://api.github.com/users/go-gopher/orgs",
                "received_events_url": "https://api.github.com/users/go-gopher/received_events",
                "repos_url": "https://api.github.com/users/go-gopher/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/go-gopher/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/go-gopher/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/go-gopher"
              },
              "permissions": {
                "admin": true,
                "pull": true,
                "push": true
              },
              "private": false,
              "pulls_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/pulls{/number}",
              "pushed_at": "2016-08-08T17:07:24Z",
              "releases_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/releases{/id}",
              "size": 0,
              "ssh_url": "git@github.com:go-gopher/test-gophers-estelle.rath.git",
              "stargazers_count": 0,
              "stargazers_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/stargazers",
              "statuses_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/statuses/{sha}",
              "subscribers_count": 1,
              "subscribers_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/subscribers",
              "subscription_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/subscription",
              "svn_url": "https://github.com/go-gopher/test-gophers-estelle.rath",
              "tags_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/tags",
              "teams_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/teams",
              "trees_url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath/git/trees{/sha}",
              "updated_at": "2016-08-08T17:07:23Z",
              "url": "https://api.github.com/repos/go-gopher/test-gophers-estelle.rath",
              "watchers": 0,
              "watchers_count": 0
            }