+ Response 201

    + Headers

            Content-Length: 5051
            Access-Control-Allow-Origin: *
            Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
            Cache-Control: private, max-age=60, s-maxage=60
            Content-Security-Policy: default-src 'none'
            Content-Type: application/json; charset=utf-8
            Date: Sat, 11 Jun 2016 12:23:17 GMT
            Etag: "e1d1d2040dcf6b1f19ae660030f96cd9"
            Location: https://api.github.com/repos/go-gopher/test-gophers-mya
            Server: GitHub.com
            Status: 201 Created
            Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
            Vary: Accept, Authorization, Cookie, X-GitHub-OTP
            Vary: Accept-Encoding
            X-Accepted-Oauth-Scopes: public_repo, repo
            X-Content-Type-Options: nosniff
            X-Frame-Options: deny
            X-Github-Media-Type: github.v3; format=json
            X-Github-Request-Id: 256E73C5:B216:28FA8051:575C02B5
            X-Oauth-Scopes: delete_repo, public_repo, read:org
            X-Ratelimit-Limit: 5000
            X-Ratelimit-Remaining: 4972
            X-Ratelimit-Reset: 1465651109
            X-Served-By: 2d7a5e35115884240089368322196939
            X-Xss-Protection: 1; mode=block

    + Body

            {
              "archive_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/{archive_format}{/ref}",
              "assignees_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/assignees{/user}",
              "blobs_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/git/blobs{/sha}",
              "branches_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/branches{/branch}",
              "clone_url": "https://github.com/go-gopher/test-gophers-mya.git",
              "collaborators_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/collaborators{/collaborator}",
              "comments_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/comments{/number}",
              "commits_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/commits{/sha}",
              "compare_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/compare/{base}...{head}",
              "contents_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/contents/{+path}",
              "contributors_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/contributors",
              "created_at": "2016-06-11T12:23:17Z",
              "default_branch": "master",
              "deployments_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/deployments",
              "description": null,
              "downloads_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/downloads",
              "events_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/events",
              "fork": false,
              "forks": 0,
              "forks_count": 0,
              "forks_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/forks",
              "full_name": "go-gopher/test-gophers-mya",
              "git_commits_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/git/commits{/sha}",
              "git_refs_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/git/refs{/sha}",
              "git_tags_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/git/tags{/sha}",
              "git_url": "git://github.com/go-gopher/test-gophers-mya.git",
              "has_downloads": true,
              "has_issues": true,
              "has_pages": false,
              "has_wiki": true,
              "homepage": null,
              "hooks_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/hooks",
              "html_url": "https://github.com/go-gopher/test-gophers-mya",
              "id": 6.0905876e+07,
              "issue_comment_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/issues/comments{/number}",
              "issue_events_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/issues/events{/number}",
              "issues_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/issues{/number}",
              "keys_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/keys{/key_id}",
              "labels_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/labels{/name}",
              "language": null,
              "languages_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/languages",
              "merges_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/merges",
              "milestones_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/milestones{/number}",
              "mirror_url": null,
              "name": "test-gophers-mya",
              "network_count": 0,
              "notifications_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/notifications{?since,all,participating}",
              "open_issues": 0,
              "open_issues_count": 0,
              "owner": {
                "avatar_url": "https://avatars.githubusercontent.com/u/19872809?v=3",
                "events_url": "https://api.github.com/users/go-gopher/events{/privacy}",
                "followers_url": "https://api.github.com/users/go-gopher/followers",
                "following_url": "https://api.github.com/users/go-gopher/following{/other_user}",
                "gists_url": "https://api.github.com/users/go-gopher/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/go-gopher",
                "id": 1.9872809e+07,
                "login": "go-gopher",
                "organizations_url": "https://api.github.com/users/go-gopher/orgs",
                "received_events_url": "https://api.github.com/users/go-gopher/received_events",
                "repos_url": "https://api.github.com/users/go-gopher/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/go-gopher/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/go-gopher/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/go-gopher"
              },
              "permissions": {
                "admin": true,
                "pull": true,
                "push": true
              },
              "private": false,
              "pulls_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/pulls{/number}",
              "pushed_at": "2016-06-11T12:23:17Z",
              "releases_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/releases{/id}",
              "size": 0,
              "ssh_url": "git@github.com:go-gopher/test-gophers-mya.git",
              "stargazers_count": 0,
              "stargazers_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/stargazers",
              "statuses_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/statuses/{sha}",
              "subscribers_count": 1,
              "subscribers_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/subscribers",
              "subscription_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/subscription",
              "svn_url": "https://github.com/go-gopher/test-gophers-mya",
              "tags_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/tags",
              "teams_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/teams",
              "trees_url": "https://api.github.com/repos/go-gopher/test-gophers-mya/git/trees{/sha}",
              "updated_at": "2016-06-11T12:23:17Z",
              "url": "https://api.github.com/repos/go-gopher/test-gophers-mya",
              "watchers": 0,
              "watchers_count": 0
            }