FORMAT: 1A
HOST: https://api.github.com

# Github API (Gophers example)

# Group Repository

## Create [POST /user/repos]

Creates a new repository for the authenticated user.

<!-- include(repo_create_request.apib) -->

<!-- include(repo_create_response.apib) -->

<!-- include(repo_create_exist_response.apib) -->
