+ Response 200

    + Headers

            Content-Length: 6486
            Accept-Ranges: bytes
            Age: 2369716
            Cache-Control: max-age=1800
            Connection: keep-alive
            Content-Type: image/png
            Date: Fri, 01 Apr 2016 07:22:46 GMT
            Fastly-Debug-Digest: 9a057a961a2b8a289986dbe6beb7b7a1d04ea8a18c458086020848aaf1040b2f
            Server: imgix-fe
            X-Imgix-Request-Id: 945cae09570498965337ad4fcc7cc7f1e416e9b4

    + Body

            [6486 bytes data]