+ Response 200

    + Headers

            Content-Length: 6486
            Accept-Ranges: bytes
            Age: 1520145
            Cache-Control: max-age=1800
            Connection: keep-alive
            Content-Type: image/png
            Date: Mon, 23 May 2016 11:23:16 GMT
            Fastly-Debug-Digest: 9a057a961a2b8a289986dbe6beb7b7a1d04ea8a18c458086020848aaf1040b2f
            Server: imgix-fe
            X-Cache: HIT, HIT
            X-Cache-Hits: 2, 613
            X-Content-Type-Options: nosniff
            X-Imgix-Request-Id: da0b3fd5fbbb29b2bb27fa04e6432a005052e457
            X-Served-By: cache-lax1431-LAX, cache-ams4425-AMS

    + Body

            [6486 bytes data]