+ Response 200

    + Headers

            Content-Length: 6486
            Accept-Ranges: bytes
            Age: 1612441
            Cache-Control: max-age=1800
            Connection: keep-alive
            Content-Type: image/png
            Date: Mon, 25 Jul 2016 13:01:34 GMT
            Fastly-Debug-Digest: 9a057a961a2b8a289986dbe6beb7b7a1d04ea8a18c458086020848aaf1040b2f
            Server: imgix-fe
            X-Cache: HIT, HIT
            X-Cache-Hits: 1, 1815
            X-Content-Type-Options: nosniff
            X-Imgix-Request-Id: 614924fc46051911a8be2773485508733c8ee3a2
            X-Imgix-Wait: 0
            X-Served-By: cache-lax1421-LAX, cache-fra1245-FRA

    + Body

            [6486 bytes data]