+ Response 200

    + Headers

            Content-Length: 6486
            Accept-Ranges: bytes
            Age: 1384848
            Cache-Control: max-age=1800
            Connection: keep-alive
            Content-Type: image/png
            Date: Fri, 23 Sep 2016 08:41:00 GMT
            Fastly-Debug-Digest: 9a057a961a2b8a289986dbe6beb7b7a1d04ea8a18c458086020848aaf1040b2f
            Server: imgix-fe
            X-Cache: HIT, HIT
            X-Cache-Hits: 2392, 28
            X-Content-Type-Options: nosniff
            X-Imgix-Request-Id: a3997318bce3ebd6e0692937d7c5abd69a1d64ac
            X-Imgix-Wait: 0
            X-Served-By: cache-lax8636-LAX, cache-fra1229-FRA

    + Body

            [6486 bytes data]