+ Response 200

    + Headers

            Content-Length: 6486
            Accept-Ranges: bytes
            Age: 1658511
            Cache-Control: max-age=1800
            Connection: keep-alive
            Content-Type: image/png
            Date: Mon, 26 Sep 2016 12:42:04 GMT
            Fastly-Debug-Digest: 9a057a961a2b8a289986dbe6beb7b7a1d04ea8a18c458086020848aaf1040b2f
            Server: imgix-fe
            X-Cache: HIT, HIT
            X-Cache-Hits: 2392, 4
            X-Content-Type-Options: nosniff
            X-Imgix-Request-Id: a639c9fa98205ce4c06f8dfd00ba873acfcfecc3
            X-Imgix-Wait: 0
            X-Served-By: cache-lax8636-LAX, cache-fra1228-FRA

    + Body

            [6486 bytes data]